---
version: 1
system_config:
  ic_type: 2
  communication_modes: 1
  device_flags: 2
  pwr_pin: 255
  pwr_pin_2: 255
  pwr_pin_3: 255
manufacturer_data:
  manufacturer_id: 1
  board_type: 0
  board_revision: 0
  simple_config_driver_index: 0
  simple_config_display_index: 0
  simple_config_power_index: 0
  simple_config_configured_at: 0
power_option:
  power_mode: 1
  battery_capacity_mah: 0
  sleep_timeout_ms: 30000
  tx_power: 0
  sleep_flags: 0
  battery_sense_pin: 1
  battery_sense_enable_pin: 6
  battery_sense_flags: 0
  capacity_estimator: 5
  voltage_scaling_factor: 161
  deep_sleep_current_ua: 0
  deep_sleep_time_seconds: 0
  charge_enable_pin: 255
  charge_state_pin: 255
  charger_flags: 0
  min_wake_time_seconds: 120
  screen_timeout_seconds: 5
displays:
  - instance_number: 0
    display_technology: 1
    panel_ic_type: 21
    pixel_width: 800
    pixel_height: 480
    active_width_mm: 163
    active_height_mm: 98
    legacy_tag_type: 0
    rotation: 0
    reset_pin: 38
    busy_pin: 4
    dc_pin: 10
    cs_pin: 44
    data_pin: 9
    partial_update_support: 0
    color_scheme: 5
    transmission_modes: 27
    clk_pin: 7
    cs_pin_2: 255
    reserved_pin_3: 255
    reserved_pin_4: 255
    reserved_pin_5: 255
    reserved_pin_6: 255
    reserved_pin_7: 255
    reserved_pin_8: 255
    full_update_mC: 4000
binary_inputs:
  - instance_number: 0
    input_type: 1
    display_as: 0
    input_pin_1: 2
    input_pin_2: 3
    input_pin_3: 5
    input_pin_4: 255
    input_pin_5: 255
    input_pin_6: 255
    input_pin_7: 255
    input_pin_8: 255
    pins_used: 7
    invert: 7
    pullups: 7
    pulldowns: 0
    button_data_byte_index: 0
    power_off_flags: 0
    power_off_hold_sec: 0
